/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikonversisuhuu;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Aplikasikonersisuhuform extends javax.swing.JFrame {
    private boolean isKonversiOtomatisAktif = false;
    /**
     * Creates new form Aplikasikonersisuhuform
     */
    public Aplikasikonersisuhuform() {
         initComponents();
        
    inisialisasiButtonGroup();

    // Tambahkan DocumentListener untuk konversi otomatis pada jTextFieldinput
    jTextFieldinput.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        if (isKonversiOtomatisAktif) {
            konversiOtomatis();
        }
    }

    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        if (isKonversiOtomatisAktif) {
            konversiOtomatis();
        }
    }

    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        if (isKonversiOtomatisAktif) {
            konversiOtomatis();
        }
    }
});

    }
     private void inisialisasiButtonGroup() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup1.add(jRadioButtoncelcius);
        buttonGroup1.add(jRadioButtonFahreinheit);
        buttonGroup1.add(jRadioButtonReamur);
        buttonGroup1.add(jRadioButtonKelvin);
    }
     private javax.swing.ButtonGroup buttonGroup1;

    // Method untuk melakukan konversi suhu
    private double konversiSuhu(double suhu, String skalaAwal, String skalaTujuan) {
        switch (skalaAwal) {
            case "Celcius":
                if (skalaTujuan.equals("Fahreinheit")) return (suhu * 9/5) + 32;
                if (skalaTujuan.equals("Reamur")) return suhu * 4/5;
                if (skalaTujuan.equals("Kelvin")) return suhu + 273.15;
                break;
            case "Fahreinheit":
                if (skalaTujuan.equals("Celcius")) return (suhu - 32) * 5/9;
                if (skalaTujuan.equals("Reamur")) return (suhu - 32) * 4/9;
                if (skalaTujuan.equals("Kelvin")) return (suhu - 32) * 5/9 + 273.15;
                break;
            case "Reamur":
                if (skalaTujuan.equals("Celcius")) return suhu * 5/4;
                if (skalaTujuan.equals("Fahreinheit")) return (suhu * 9/4) + 32;
                if (skalaTujuan.equals("Kelvin")) return suhu * 5/4 + 273.15;
                break;
            case "Kelvin":
                if (skalaTujuan.equals("Celcius")) return suhu - 273.15;
                if (skalaTujuan.equals("Fahreinheit")) return (suhu - 273.15) * 9/5 + 32;
                if (skalaTujuan.equals("Reamur")) return (suhu - 273.15) * 4/5;
                break;
        }
        return suhu;
    }
    private void konversiOtomatis() {
     if (!isKonversiOtomatisAktif) return;

    try {
        // Cek apakah input kosong
        if (jTextFieldinput.getText().isEmpty()) {
            jTextFieldhasil.setText("");
            return;
        }

        double suhuAwal = Double.parseDouble(jTextFieldinput.getText());
        String skalaAwal = (String) jComboBoxskalaawal.getSelectedItem();

        String skalaTujuan = "";
        if (jRadioButtoncelcius.isSelected()) skalaTujuan = "Celcius";
        else if (jRadioButtonFahreinheit.isSelected()) skalaTujuan = "Fahreinheit";
        else if (jRadioButtonReamur.isSelected()) skalaTujuan = "Reamur";
        else if (jRadioButtonKelvin.isSelected()) skalaTujuan = "Kelvin";

        if (!skalaTujuan.isEmpty()) {
            double hasilKonversi = konversiSuhu(suhuAwal, skalaAwal, skalaTujuan);
            jTextFieldhasil.setText(String.format("%.2f %s", hasilKonversi, skalaTujuan));
        }
    } catch (NumberFormatException e) {
        jTextFieldhasil.setText("Input tidak valid");
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtoncelcius = new javax.swing.JRadioButton();
        jRadioButtonFahreinheit = new javax.swing.JRadioButton();
        jRadioButtonReamur = new javax.swing.JRadioButton();
        jRadioButtonKelvin = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxskalaawal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldinput = new javax.swing.JTextField();
        jButtonhitung = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldhasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Konversi Suhu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 0, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jRadioButtoncelcius.setText("Celcius");

        jRadioButtonFahreinheit.setText("Fahreinheit");

        jRadioButtonReamur.setText("Reamur");

        jRadioButtonKelvin.setText("Kelvin");
        jRadioButtonKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKelvinActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pilih hasil konversi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtoncelcius)
                            .addComponent(jRadioButtonFahreinheit)
                            .addComponent(jRadioButtonReamur)
                            .addComponent(jRadioButtonKelvin)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jRadioButtoncelcius)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFahreinheit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonReamur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonKelvin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxskalaawal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahreinheit", "Reamur", "Kelvin" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pilih suhu yang ingin anda rubah");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Input nilai ");

        jTextFieldinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldinputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldinput)
                            .addComponent(jComboBoxskalaawal, 0, 158, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jComboBoxskalaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonhitung.setText("Hitung");
        jButtonhitung.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhitungActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hasil konversi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldhasil)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonhitung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonclear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonKelvinActionPerformed

    private void jButtonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhitungActionPerformed
      try {
        double suhuAwal = Double.parseDouble(jTextFieldinput.getText());
        String skalaAwal = (String) jComboBoxskalaawal.getSelectedItem();

        String skalaTujuan = "";
        if (jRadioButtoncelcius.isSelected()) skalaTujuan = "Celcius";
        else if (jRadioButtonFahreinheit.isSelected()) skalaTujuan = "Fahreinheit";
        else if (jRadioButtonReamur.isSelected()) skalaTujuan = "Reamur";
        else if (jRadioButtonKelvin.isSelected()) skalaTujuan = "Kelvin";

        double hasilKonversi = konversiSuhu(suhuAwal, skalaAwal, skalaTujuan);
        jTextFieldhasil.setText(String.format("%.2f %s", hasilKonversi, skalaTujuan));

        // Aktifkan konversi otomatis setelah hitung
        isKonversiOtomatisAktif = true;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonhitungActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
 jTextFieldinput.setText("");
    jTextFieldhasil.setText("");
    jComboBoxskalaawal.setSelectedIndex(0);
    buttonGroup1.clearSelection();

    // Nonaktifkan konversi otomatis
    isKonversiOtomatisAktif = false;
    }//GEN-LAST:event_jButtonclearActionPerformed
private void resetKonversiOtomatis() {
    jTextFieldinput.setText("");
    jTextFieldhasil.setText("");
    jComboBoxskalaawal.setSelectedIndex(0);
    buttonGroup1.clearSelection();
}
    
    private void jTextFieldinputKeyTyped(java.awt.event.KeyEvent evt) {
    char c = evt.getKeyChar();
    String currentText = jTextFieldinput.getText();
    
    if (Character.isDigit(c)) {
        return; // Izinkan angka
    } else if (c == '-' && currentText.isEmpty()) {
        return; // Izinkan tanda minus hanya di awal
    } else if (c == '.' && !currentText.contains(".") && !currentText.isEmpty()) {
        return; // Izinkan satu titik desimal
    } else {
        evt.consume(); // Blokir karakter yang tidak valid
        JOptionPane.showMessageDialog(this, 
            "Hanya boleh memasukkan angka, tanda minus (-) di awal, dan titik desimal (.)", 
            "Input Tidak Valid", 
            JOptionPane.WARNING_MESSAGE);
    }
}




 
    private void jTextFieldinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldinputActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldinputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasikonersisuhuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasikonersisuhuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasikonersisuhuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasikonersisuhuform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Aplikasikonersisuhuform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonhitung;
    private javax.swing.JComboBox<String> jComboBoxskalaawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonFahreinheit;
    private javax.swing.JRadioButton jRadioButtonKelvin;
    private javax.swing.JRadioButton jRadioButtonReamur;
    private javax.swing.JRadioButton jRadioButtoncelcius;
    private javax.swing.JTextField jTextFieldhasil;
    private javax.swing.JTextField jTextFieldinput;
    // End of variables declaration//GEN-END:variables

}
